base_url = "https://luciano.live"
title = "Luciano Scarpulla"
description = "Personal blog about coding, aviation and more."
author = "luciano"
compile_sass = true
build_search_index = false
generate_feeds = true
generate_sitemap = true
feed_limit = 10

taxonomies = [{ name = "tags" }]

[markdown]
highlighting = { style = "inline", light_theme = "gruvbox-light-medium", dark_theme = "gruvbox-dark-medium" }
smart_punctuation = true
lazy_async_image = true
external_links_target_blank = true
external_links_class = "external"
insert_anchor_links = "right"

[extra]
github = "https://github.com/lucianosrp"
email = "mailto:scarpulla53@gmail.com"
